# fly.toml file generated for bitter-wave-2510 on 2022-07-29T19:31:12-04:00

app = "bitter-wave-2510"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    BUNDLER_VERSION = "2.3.16"
    NODE_VERSION = "14"
    RUBY_VERSION = "3.1.1"

[deploy]

[env]
  PORT = "8080"
  SERVER_COMMAND = "bundle exec rackup config.ru -p 8080 -o 0.0.0.0"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
